module Lorem exposing (lorem)


lorem =
    """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque condimentum sem eu molestie sollicitudin. Integer ut ligula faucibus, tempus purus quis, molestie nulla. Vestibulum ultrices feugiat tempor. Nulla eu suscipit ante. Vestibulum neque nisl, varius vitae vehicula sit amet, malesuada facilisis ligula. Fusce luctus id lorem sed porttitor. Donec vel turpis nibh. Praesent et dictum libero. Vivamus ornare ex congue elit euismod tempor. Fusce pretium ipsum sit amet vehicula fermentum. Sed commodo turpis urna, vel maximus erat feugiat sodales. Quisque semper velit sem, vel ornare enim consectetur elementum.

Nunc ligula nisi, pretium vitae nunc et, volutpat molestie arcu. In imperdiet, eros ac facilisis imperdiet, nunc libero molestie est, eget fringilla mi ante ut tellus. Duis facilisis finibus sapien eu ultrices. Sed sed velit consectetur, porta lacus ultricies, congue neque. Donec dignissim est felis, nec eleifend quam mollis sit amet. Mauris enim quam, efficitur ut dolor sed, viverra porta odio. Aenean volutpat convallis semper. Donec malesuada dignissim dolor ut placerat. Aliquam cursus nisi eget tempus tempus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc accumsan, augue vel aliquet efficitur, ipsum orci iaculis tortor, a consequat justo elit in nisi. Nunc molestie non nisi vel volutpat. Mauris feugiat, erat placerat placerat placerat, nunc mi vehicula lacus, ut fermentum metus ante eget est. Quisque malesuada ipsum venenatis, interdum justo vitae, fermentum ipsum.

Vivamus tempus mattis bibendum. Suspendisse vitae scelerisque sem. Morbi eros diam, rhoncus ac velit quis, pulvinar faucibus ante. Vestibulum ut magna sed ipsum vehicula elementum a vitae nisl. Proin convallis lectus in vehicula scelerisque. Sed viverra, velit vel malesuada vulputate, lectus urna sodales est, quis tempor erat orci non ipsum. Nulla orci nulla, tristique eu nibh quis, pharetra lacinia lacus. Mauris elementum ultricies vulputate. Duis et leo eros. Ut efficitur odio lorem, ac vestibulum mi congue sit amet. Nam a sapien et nibh viverra lobortis non in nisi. Nam vel sem nulla. Praesent fringilla est ac luctus lacinia. Integer iaculis erat nec eleifend egestas.

Mauris et eros quis erat hendrerit convallis. Nulla vehicula, ante at vestibulum vestibulum, mi turpis euismod sem, bibendum porttitor nisi urna suscipit massa. Sed tortor metus, finibus sed vehicula ac, aliquam ut diam. Maecenas commodo cursus erat, nec mattis dolor ullamcorper a. Sed ex arcu, euismod ut lacinia at, rutrum nec neque. Aenean accumsan quam sed orci auctor rhoncus. Nulla tempor luctus maximus.

Pellentesque lorem erat, semper sed vehicula congue, volutpat quis metus. Nunc et elementum augue. In placerat dolor ante, in condimentum augue sollicitudin in. Vestibulum sollicitudin pulvinar mi, eu congue tellus ullamcorper eget. In libero nunc, mattis ac porttitor sit amet, mattis ut magna. Maecenas turpis tellus, blandit eget vestibulum quis, rutrum bibendum ex. Pellentesque euismod est dui, et vestibulum leo pulvinar sed. Integer malesuada dolor nec elit volutpat dictum. Vestibulum pellentesque efficitur scelerisque. Vivamus vestibulum consequat consectetur.

Mauris felis ipsum, tincidunt et nisl vel, vehicula lobortis justo. Praesent placerat vestibulum mauris quis lobortis. Morbi aliquet hendrerit nibh, eu lobortis quam rutrum in. Sed malesuada mi vitae turpis pulvinar varius. Nulla faucibus felis sit amet nibh iaculis porta. Vestibulum sodales ex vel ultricies vehicula. Nullam commodo enim et purus convallis auctor. Etiam eu eros lacus. Duis sit amet nisi vel lacus ornare dignissim et at lectus.

Suspendisse potenti. Phasellus laoreet risus eget ante tempus, vitae faucibus justo consequat. Proin porta nulla semper blandit facilisis. Nullam volutpat ut elit et aliquam. Nunc pretium urna non velit volutpat porta. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra vel urna a fringilla. Suspendisse blandit risus in euismod sodales. Sed in dolor sit amet mauris semper dapibus non eget sem.

Quisque id luctus nulla. Cras nisl tellus, mollis volutpat augue sollicitudin, ornare pulvinar mauris. Phasellus gravida dolor non imperdiet molestie. Integer vel risus nibh. Proin consequat fringilla finibus. Integer sed finibus purus. Maecenas nunc enim, vehicula ut vestibulum nec, iaculis nec velit. Donec interdum risus quis tincidunt pellentesque. Nunc gravida sem imperdiet erat pharetra lacinia. Duis lobortis nec urna ut semper.

Nulla accumsan malesuada fermentum. Morbi posuere quam in justo dapibus, a porttitor sem ornare. Aenean in turpis elit. Aenean hendrerit urna mauris, a bibendum dolor venenatis ut. Nulla dictum posuere nisi id porta. Donec eu dolor venenatis, scelerisque nisi non, consectetur nisi. In placerat nec nulla eu porta. Aliquam ullamcorper leo id tempus condimentum. Aenean vulputate non velit vitae interdum. Morbi risus est, placerat ac nibh sit amet, vestibulum rhoncus neque. Duis sit amet auctor neque. Sed ac varius lacus. Vestibulum eu quam ac lacus semper ultrices. Mauris lobortis imperdiet tortor, et pellentesque tortor suscipit non. Nunc porttitor neque et neque sollicitudin, at sagittis diam auctor.

Proin ipsum turpis, dictum quis mauris vitae, placerat interdum sapien. Maecenas sit amet lectus ac ex convallis condimentum at eget lorem. Fusce tristique arcu semper massa vulputate feugiat. Donec lobortis iaculis tellus. Integer nunc sem, gravida quis porttitor volutpat, semper interdum justo. Aenean volutpat varius elit. Maecenas ultricies interdum purus vitae auctor.

Nullam scelerisque consectetur nibh. Nunc leo sem, gravida ac pretium nec, tempus quis odio. Nulla tempus ultrices sollicitudin. Etiam non placerat justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur hendrerit facilisis ultrices. Aliquam sollicitudin fermentum lectus eu consectetur. Vivamus interdum eros vitae ex rhoncus luctus. Sed ultrices ac urna eget bibendum. Nulla facilisi. In blandit neque posuere convallis accumsan. Nam vulputate nisi non purus interdum maximus. Aliquam faucibus sem quis aliquet scelerisque. Donec ut congue massa, sit amet ultricies felis. Phasellus ultricies nec orci eu hendrerit. Ut sit amet erat nec nisi eleifend dignissim.

Etiam tincidunt egestas nisl, at ultrices ipsum suscipit sagittis. Cras quis dictum arcu. Sed lacus lacus, lobortis sed leo quis, ornare ullamcorper nunc. Fusce malesuada elementum ex, ut aliquet ex posuere a. Donec sagittis erat id auctor maximus. Donec ullamcorper diam et elementum pulvinar. Donec quis vehicula est. Integer egestas aliquet turpis, quis iaculis lectus dapibus quis.

Aenean scelerisque malesuada elementum. Donec sed lorem est. Suspendisse potenti. Integer nec dolor nisi. Aenean accumsan quam lacinia odio interdum iaculis. Ut eget accumsan lacus. Duis maximus, metus in posuere iaculis, quam justo fringilla leo, sed vulputate enim odio et neque. Aenean facilisis, orci vel convallis pharetra, tellus ipsum convallis nisl, ac scelerisque lorem erat a mauris. In hac habitasse platea dictumst. Morbi ultrices bibendum condimentum. Ut et neque venenatis leo faucibus condimentum at id dolor.

Vestibulum euismod, ligula quis rhoncus facilisis, dui metus scelerisque libero, eu dignissim massa urna nec arcu. Praesent sit amet arcu et purus euismod dictum. Ut imperdiet sollicitudin sapien, faucibus vehicula metus vestibulum sit amet. Nunc feugiat pulvinar diam, et maximus ligula dignissim non. Proin sed aliquet turpis, eu facilisis dolor. Etiam bibendum sapien non quam lobortis euismod. Mauris maximus mi mi, eu feugiat lectus blandit vitae.

Morbi eget nisl eget augue dignissim euismod quis eu eros. Nunc a ullamcorper velit. Nullam aliquet quis sapien eget fermentum. Suspendisse potenti. Aliquam viverra ante tortor, id dapibus orci pharetra at. Curabitur suscipit aliquet nulla ac convallis. Vestibulum sapien lectus, volutpat at sagittis sed, dictum sit amet diam.

Sed posuere, neque a suscipit posuere, massa est feugiat justo, eget mollis nisi tortor quis elit. Cras consectetur et arcu vitae luctus. In vitae odio nibh. In hac habitasse platea dictumst. Nam vitae sapien iaculis, consequat erat a, ornare dui. Donec pretium aliquam fringilla. Praesent nulla leo, viverra in sapien non, porta ornare tortor.

Donec accumsan maximus nisi, eget mollis ligula pellentesque at. In efficitur dui lectus, non ultricies ex accumsan id. Proin varius maximus purus, vel dictum nisi faucibus porttitor. Morbi est mauris, gravida ut quam id, tincidunt imperdiet dolor. Proin vulputate tincidunt dui auctor mattis. Morbi non tellus eu mauris convallis elementum nec et mi. Nam laoreet eros nec enim luctus dapibus. Etiam vel ex luctus, bibendum justo sed, viverra augue. Proin vehicula nunc sit amet ullamcorper auctor. Nulla varius dui magna, feugiat dignissim lacus lobortis ut. Sed interdum efficitur est egestas scelerisque. Vestibulum eget purus efficitur purus vulputate placerat. Quisque at sem nibh.

Sed in dolor id urna aliquet ultrices. Curabitur vitae euismod enim. Nulla fermentum est nibh. Mauris feugiat dui in libero lacinia lobortis. Vestibulum risus turpis, rutrum nec ante vel, scelerisque porttitor ante. Aliquam venenatis erat et massa elementum, sit amet posuere erat rhoncus. Donec maximus mi in arcu pharetra, eu gravida leo pellentesque.

Sed ullamcorper purus vitae elementum sagittis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec aliquam dui quis pellentesque lacinia. Praesent metus arcu, aliquam porttitor dignissim eget, malesuada congue est. Maecenas egestas, mauris at gravida laoreet, odio risus laoreet velit, sed aliquet odio mauris in eros. Curabitur non lacinia sapien. Aliquam ornare risus tellus, sed ultrices purus luctus at. Cras tincidunt efficitur ante, bibendum sodales neque fringilla sed.

Phasellus ut accumsan tortor. Vivamus tempus urna enim. Integer auctor gravida augue, in pellentesque ante sagittis sit amet. Nulla vitae dapibus enim, ac ultricies nunc. Nulla molestie nulla arcu, id eleifend tortor elementum non. Praesent lectus diam, ornare eget congue in, euismod ut nisl. Donec pharetra ut quam vel tristique. Fusce in eros sed leo lobortis ultricies. In volutpat luctus ligula. In hac habitasse platea dictumst. Nam vel viverra odio. Quisque risus risus, bibendum quis maximus nec, tristique et justo. Curabitur urna sapien, tempus et condimentum vel, blandit id velit. Suspendisse faucibus, leo pulvinar molestie volutpat, purus dolor pulvinar nisi, ut aliquam sem sem vitae nisl. Sed consectetur rhoncus ullamcorper. Curabitur consectetur risus nec dictum commodo.
"""
